spring:
  datasource:
    username: root
    password: win!@3456
    url: jdbc:mysql://localhost:3306/h5-renewal
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
  security:
    user:
      password: 1234

    oauth2:
      client:
        registration:
          kakao:
            client-id: 7860f549c4d706924b097851c673b0c7
            redirect-uri: http://localhost:8080/login/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: kakao
            scope:
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id